config:
  issuer: toreplacedbyissuer
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: debug
  expiry:
    signingKeys: "6h"
    idTokens: "1h"
  web:
    https: "0.0.0.0:443"
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      issuer: toreplacedbyissuer
      # No TLS for this setup.
      insecureNoSSL: false
      rootCA: /etc/dex/ca/ldap.ca
      # This would normally be a read-only user.
      bindDN: "cn=readonly,dc=example,dc=org"
      bindPW: readonly
      groupSearch:
        baseDN: "ou=Groups,dc=example,dc=org"
        filter: (objectClass=groupOfNames)
        groupAttr: member
        nameAttr: cn
        userAttr: DN
      host: "toreplacebyldapaddress"
      userSearch:
        baseDN: "ou=People,dc=example,dc=org"
        emailAttr: mail
        filter: (objectClass=person)
        idAttr: DN
        nameAttr: cn
        username: mail
      usernamePrompt: "Email Address"
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - id: example-app
    redirectURIs:
    - 'http://127.0.0.1:5555/callback'
    - 'urn:ietf:wg:oauth:2.0:oob'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
rootCAsecret: root-ca
rootCAfile: certs/ldap.ca
