apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: inference-endpoints.ai.intel.com
  namespace: {{ .Values.namespace }}
spec:
  group: ai.intel.com
  version: v1
  scope: Namespaced
  names:
    plural: inference-endpoints
    singular: inference-endpoint
    kind: InferenceEndpoint
    shortNames:
    - ie
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - modelName
            - modelVersion
            - endpointName
            - subjectName
          properties:
            modelName:
              type: string
              minLength: 3
            modelVersion:
              type: integer
              format: int32
              minimum: 1
            endpointName:
              type: string
              minLength: 3
            subjectName:
              type: string
              pattern: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
            resources:
              type: object
              properties:
                additionalProperties:
                  type: string
            replicas:
              type: integer
              format: int32
              minimum: 0
