apiVersion: v1
kind: Secret
metadata:
  name: ca-ing
  namespace: dex 
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "ca.crt": |-
  {{ .Files.Get "certs/ca-ing.crt" | b64enc | indent 4 }}
