{{ if .Values.cert_files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs_secret }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.cert_files }}
  {{ $key }}: |-
  {{ $.Files.Get $val | b64enc | indent 4 }}
  {{- end }}
{{ end }}


