#
# A Secret spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
{{- if .Values.customLdifFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}-customldif
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}

type: Opaque

data:
  immconfig.ldif: {{ .Values.customLdifFiles.ldif | replace "*password*" (randAlphaNum 8) | b64enc | quote }}

{{ end }}
